### ISSUE TITLE
yegrb.com social sidebar updates

### ISSUE THREAD

**Issue by nathany** [yegrb/yegrb.github.io#7]
Short-term updates
1. Our YouTube channel is empty. There are some videos [under Mark's channel](http://www.youtube.com/user/runningboy311/videos), but I don't know they can be moved.
2. Do we want to link to a different calendar? [Startup](http://startupedmonton.com/calendar/) or [Abram's](https://www.google.com/calendar/embed?src=vunju25ipafbs91qmqv6nthmeg%40group.calendar.google.com&ctz=America/Denver) or keep one specific to YEGRB.
3. Do we want to keep IRC? Provide instructions for using a desktop client like Colloquy?
4. Do we want the mailing list as "subscribe" or just link right to Google Groups?

**Comment by alanvardy** [comment]
Expired, some changes have been made.
